defaults: &defaults
  working_directory: /go/src/github.com/sbstjn/predown
  docker:
    - image: jimdo/golang-dep

version: 2

releases: &releases
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Gopkg.toml" }}

      - run:
          name: Install dependencies
          command: dep ensure

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Gopkg.toml" }}
          paths:
            - vendor

      - persist_to_workspace:
          root: .
          paths:
            - Makefile
            - vendor
            - "*.go"
            - ".git"

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run linter
          command: make lint

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run tests
          command: make test

      - persist_to_workspace:
          root: .
          paths:
            - c.out

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Build darwin
          command: VERSION=${CIRCLE_TAG:1} GOOS=darwin make build

      - run:
          name: Build linux
          command: VERSION=${CIRCLE_TAG:1} GOOS=linux make build

      - persist_to_workspace:
          root: .
          paths:
            - dist

  release:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Create GitHub Release
          command: |
            hub release edit v${CIRCLE_TAG:1} -m "v${CIRCLE_TAG:1}" -a dist/predown_darwin -a dist/predown_linux

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - lint
            - test
  release:
    jobs:
      - checkout:
          <<: *releases
      - lint:
          <<: *releases
          requires:
            - checkout
      - test:
          <<: *releases
          requires:
            - checkout
      - build:
          <<: *releases
          requires:
            - lint
            - test
      - release:
          <<: *releases
          requires:
            - build